#pragma once

#define REFERENCE_SCREEN_WIDTH 1440
#define REFERENCE_SCREEN_HEIGHT 900
#define TILE_SIZE 16
#define PIXELS_PER_UNIT TILE_SIZE
#define DEBUG_ENABLED true

#define DEBUG_ENABLE_STACKTRACE_LINE true
